spring:
  application:
    name: service_getway_api
  cloud:
    gateway:
      routes:
        - id: service_jwt_token
          uri: http://localhost:8081/service_jwt_token/**
          predicates:
            - Path=/**
            - Method=GET,POST
          metadata:
            cors:
              allowedOrigins: '*'
              allowedMethods:
                - GET
                - POST
              allowedHeaders: '*'
              maxAge: 30
        - id: service_admin_plant
          uri: http://localhost:8082/service_admin_plant/**
          predicates:
            - Path=/**
            - Method=GET,POST
          metadata:
            cors:
              allowedOrigins: '*'
              allowedMethods:
                - GET
                - POST
              allowedHeaders: '*'
              maxAge: 30
        - id: service_client_cart
          uri: http://localhost:8083/service_client_cart/**
          predicates:
            - Path=/**
            - Method=GET,POST
          metadata:
            cors:
              allowedOrigins: '*'
              allowedMethods:
                - GET
                - POST
              allowedHeaders: '*'
              maxAge: 30
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/